# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab2f2c815c8e74542991d06ea8b4eaef2d77d58a0a1631693cddc33dbdf5f21fcbc1726b356e1ce60f8bb7daea60cdba5da46ffa43505ecaa02fc500820b9e8b

test:
  secret_key_base: 339395b2dcdf30badbcc0f430975d4a3cf74a3556ded3485abd866fc8d5b4dba50c5aaaa894f870a3f70e156056e0c39b674623c17a5a11724a1aba378f33465

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
